### ISSUE TITLE
Fail functions prints stack trace and exits, making failure cases untestable

### ISSUE THREAD

**Issue by ContainedBlargh** [WingCorp/HighDefinitionC#6]
Looking for suggestions on how to prevent system exit when testing.
Already tried pre-compile tags.

**Comment by FlapKap** [comment]
Burde du ikke ligge i din seng makker?

**Comment by ContainedBlargh** [comment]
Går i seng nu, må stoppe med at drikke kaffe efter 20 🕦 ☕️

**Comment by ContainedBlargh** [comment]
Fixed in commit 8318ca9fda83723fa343509e92fd3f2a015fa01b.
